apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deploy-svc-probes.httpdConfConfigMapName" . }}
  labels:
    {{- include "deploy-svc-probes.commonLabels" . | nindent 4 }}
data:
  httpd.conf: |-
{{- if .Values.httpdConf.inline }}
{{ .Values.httpdConf.inline | nindent 4 }}
{{- else }}
{{ (.Files.Get "files/httpd.conf") | nindent 4 }}
{{- end }}
