apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deploy-svc-probes.extCheckerConfigMapName" . }}
  labels:
    {{- include "deploy-svc-probes.commonLabels" . | nindent 4 }}
data:
  TARGET_URL: {{ .Values.extChecker.targetUrl | quote }}
  EXTERNAL_URL: {{ .Values.extChecker.externalUrl | quote }}
